service: market-node
frameworkVersion: "2"
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_REGION}
  lambdaHashingVersion: "20201221"
  apiGateway:
    shouldStartNameWithService: true

package:
  individually: true

custom:
  serverless-offline:
    useChildProcesses: true
  webpack:
    webpackConfig: ./webpack.config.js

functions:
  product:
    handler: src/app/market/app.handler
    events:
      - http:
          path: /market
          method: ANY
          cors: true
      - http:
          path: /market/{proxy+}
          method: ANY
          cors: true
