service: market-node
frameworkVersion: "2"
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_REGION}
  lambdaHashingVersion: "20201221"
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
  serverless-offline:
    useChildProcesses: true
  dynamodb:
    start:
      migrate: true
    stages:
      - local

functions:
  product:
    handler: src/app/market/app.handler
    events:
      - http:
          path: /market
          method: ANY
          cors: true
      - http:
          path: /market/{proxy+}
          method: ANY
          cors: true

resources:
  Resources:
    ProductTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        TableName: product
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
