openapi: 3.0.0
info:
  title: Market
  version: latest
servers:
  - url: "http://localhost:3000/local"
  - url: "https://c1dmjwlayi.execute-api.us-east-1.amazonaws.com/dev"
paths:
  # $ref#product: ./product.yml#/paths
  $ref#admin#category: ./admin/category.yml#/paths
  $ref#admin#product: ./admin/product.yml#/paths
  # $ref#store: ./store.yml#/paths
components:
  schemas:
    # $ref#product: ./product.yml#/schemas
    # $ref#store: ./store.yml#/schemas
    $ref#base: ./base.yml#/schemas
  responses:
    $ref#base: ./base.yml#/responses
