paths:
  /market/product:
    post:
      description: Crea un producto
      tags:
        - Product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
      responses:
        201:
          description: "created"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
    get:
      description: Devuelve lista de productos
      tags:
        - Product
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Product"

  /market/product/{id}:
    get:
      description: Devuelve el detalle de un producto
      tags:
        - Product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
        404:
          $ref: "#/components/responses/ErrorNotFound"
    put:
      description: Actualiza un producto
      tags:
        - Product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        404:
          $ref: "#/components/responses/ErrorNotFound"

schemas:
  Product:
    type: object
    properties:
      _id:
        type: string
        readOnly: true
      title:
        type: string
      description:
        type: string
      price:
        type: number
      categories:
        type: array
        items:
          $ref: "#/components/schemas/Category"
      createdAt:
        type: string
        format: date-time
        readOnly: true
