paths:
  /admin/product:
    post:
      description: Crea un producto
      tags:
        - Admin / Product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
      responses:
        201:
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string

    get:
      description: Lista de productos
      tags:
        - Admin / Product
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number

  /admin/product/{id}:
    get:
      description: Detalle de producto
      tags:
        - Admin / Product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
        404:
          $ref: "#/components/responses/ErrorNotFound"

  /admin/product/{id}/category:
    post:
      description: Asocia la categoria a un producto
      tags:
        - Admin / Product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                categoryId:
                  type: string
      responses:
        201:
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string

    get:
      description: Lista de categorias asociadas
      tags:
        - Admin / Product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string

  /admin/product/{id}/category/{categoryId}:
    delete:
      description: Elimina asociación de categoria con producto
      tags:
        - Admin / Product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: categoryId
          in: path
          required: true
          schema:
            type: string
      responses:
        201:
          description: ok
