openapi: 3.0.0
info:
  title: Market
  version: latest
servers:
  - url: 'http://localhost:3000/local'
  - url: 'https://c1dmjwlayi.execute-api.us-east-1.amazonaws.com/dev'
paths:
  /admin/category:
    post:
      description: Crea una categoria
      tags:
        - Admin / Category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
    get:
      description: Lista de categorias
      tags:
        - Admin / Category
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
  '/admin/category/{id}':
    get:
      description: Detalle de categoria
      tags:
        - Admin / Category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
        '404':
          $ref: '#/components/responses/ErrorNotFound'
  /admin/product:
    post:
      description: Crea un producto
      tags:
        - Admin / Product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
    get:
      description: Lista de productos
      tags:
        - Admin / Product
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
  '/admin/product/{id}':
    get:
      description: Detalle de producto
      tags:
        - Admin / Product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
        '404':
          $ref: '#/components/responses/ErrorNotFound'
  '/admin/product/{id}/category':
    post:
      description: Asocia la categoria a un producto
      tags:
        - Admin / Product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                categoryId:
                  type: string
      responses:
        '201':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
  '/admin/product/{id}/category/{categoryId}':
    delete:
      description: Elimina asociación de categoria con producto
      tags:
        - Admin / Product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: categoryId
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: ok
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
  responses:
    ErrorNotFound:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
